[config]
schemaVersion = "0.0.1"

[package]
namespace = "PhoenixLegacy"
name = "Phoenix_Suits"
versionNumber = "1.0.0"
description = "Custom suits for the phoenix legacy community"
websiteUrl = "https://github.com/codakairos/phoenix-suits"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
x753-More_Suits = "1.4.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[publish]
repository = "https://thunderstore.io"
communities = ["lethal-company"]
categories = ["cosmetics"]
