name: Deploy to Thunderstore

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      TCLI_VERSION: 0.1.7

    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Install tcli
        run: |
          wget --no-verbose https://github.com/thunderstore-io/thunderstore-cli/releases/download/$TCLI_VERSION/tcli-$TCLI_VERSION-linux-x64.tar.gz \
          && tar xzf tcli-$TCLI_VERSION-linux-x64.tar.gz

      - name: Publish to Thunderstore
        run: |
          ./tcli-$TCLI_VERSION-linux-x64/tcli publish --token ${{ secrets.THUNDERSTORE_TOKEN }} --package-version ${{ env.RELEASE_VERSION }}
